### PR TITLE
Update with to support running directly on Python 3.

### PR DESCRIPTION
**Pull request by emiliadecaudin**

### CODE REVIEW

**Comment by JohnMeyerhoff** [comment]
This should be merged, works perfectly :) 
Maybe add the folders back into the project as they do not get tracked when empty but are required :)

**Comment by moghwan** [comment]
I'm having the error `Cannot find default settings` in `colorSchemeTool.log` log file, any solution ?

Python 3.10.10

**Comment by vertigomaster** [comment]
@emiliadecaudin Worked for me too! I agree with @JohnMeyerhoff

**Comment by emiliadecaudin** [comment]
Implemented by another PR.

**Pull request closed without merging**
